# SwiftLint Configuration for KDragonBall iOS App

# Rules to disable
disabled_rules:
  - trailing_whitespace
  - todo
  - line_length

# Rules to enable
opt_in_rules:
  - empty_count
  - explicit_init
  - force_unwrapping
  - closure_spacing
  - redundant_nil_coalescing
  - sorted_imports
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

# Paths to include
included:
  - iosApp

# Paths to exclude
excluded:
  - Pods
  - .build
  - build
  - DerivedData
  - '*.generated.swift'

# Rule configurations
file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 60
  error: 100

function_parameter_count:
  warning: 5
  error: 8

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 2

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50
  excluded:
    - id
    - vm
    - T
    - i

type_name:
  excluded:
    - iOSApp

large_tuple:
  warning: 3
  error: 4

# Custom rules
custom_rules:
  no_objcMembers:
    name: "@objcMembers"
    regex: "@objcMembers"
    message: "Explicitly use @objc on each member you want to expose to Objective-C"
    severity: warning

# Reporter type
reporter: "github-actions-logging"
